### ISSUE TITLE
when start gartner-client-extensions-demo got below error on windows10

### ISSUE THREAD

**Issue by simonjhy** [liferay/liferay-cli#87] opened 2022-11-04 03:13 UTC
[31mFATA[0m[0000] runtime failed to list nodes: docker failed to get containers with labels 'map[app:k3d]': failed to list containers: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22app%3Dk3d%22%3Atrue%7D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied
uid=1000
user=localdev
[36mINFO[0m[0000] Using config file /tmp/.cluster_config.yaml (k3d.io/v1alpha4#simple)
[36mINFO[0m[0000] portmapping '443:443' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy]
[36mINFO[0m[0000] Prep: Network
[31mERRO[0m[0000] Failed to get nodes for cluster 'localdev': docker failed to get containers with labels 'map[k3d.cluster:localdev]': failed to list containers: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22app%3Dk3d%22%3Atrue%2C%22k3d.cluster%3Dlocaldev%22%3Atrue%7D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied
[31mERRO[0m[0000] Failed Cluster Preparation: Failed Network Preparation: failed to create cluster network: failed to check for duplicate docker networks: docker failed to list networks: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/networks?filters=%7B%22name%22%3A%7B%22%5E%2F%3Fk3d-localdev%24%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
[31mERRO[0m[0000] Failed to create cluster >>> Rolling Back
[36mINFO[0m[0000] Deleting cluster 'localdev'
[31mERRO[0m[0000] Failed to get nodes for cluster 'localdev': docker failed to get containers with labels 'map[k3d.cluster:localdev]': failed to list containers: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22app%3Dk3d%22%3Atrue%2C%22k3d.cluster%3Dlocaldev%22%3Atrue%7D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied
[31mERRO[0m[0000] failed to get cluster: No nodes found for given cluster
[31mFATA[0m[0000] Cluster creation FAILED, also FAILED to rollback changes!

**Comment by rotty3000** [comment] 2022-11-04 13:57
Thanks for reporting @simonjhy :)

This is already fixed here https://github.com/liferay/liferay-cli/issues/83. It will be in the next release

Can try with the next branch to verify?

**Comment by rotty3000** [comment] 2022-11-14 15:28
No response assuming that the issue is resolved.

**Closed as completed by rotty3000** 2022-11-14 15:28 UTC
Labels: bug
